language: go
before_install:
 - wget https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.9.zip
 - unzip -d $HOME go_appengine_sdk_linux_amd64-*.zip
 - export PATH=$PATH:$HOME/go_appengine
install: goapp get github.com/mzimmerman/appenginetesting
script: goapp test
