language: go
before_install:
 - wget https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.5.zip
 - unzip -d $HOME go_appengine_sdk_linux_amd64-1.9.5.zip
 - ls -l
 - ls -l $HOME
 - ls -l $GOPATH
 - pwd
 - ln -s $GOPATH/src/appengine $HOME/go_appengine/goroot/src/pkg/appengine
 - ln -s $GOPATH/src/appengine_internal $HOME/go_appengine/goroot/src/pkg/appengine_internal
